version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    depends_on:
      db:
        condition: service_healthy
    command: ['npm', 'start']

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: phoenix
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 33696549
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d phoenix']
      timeout: 5s
      retries: 5

volumes:
  db-data:
